name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: KorryKatti
          config_gemoji: yes
          config_timezone: Asia/Kolkata
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_recent_days: 7
          plugin_languages_limit: 4
          plugin_topics_mode: icons
          plugin_discussions_categories_limit: 8
          plugin_languages_ignored: Berry
